import { Product, Movement, WarehouseConfig } from './types';

export const DEFAULT_CONFIG: WarehouseConfig = {
  racksCount: 6,
  shelvesCount: 5,
  positionsCount: 3,
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    sku: 'SKU-EL-3001',
    name: 'Industrial Proximity Sensor V2',
    quantity: 45,
    unit: 'count',
    location: 'R1-S1-L1',
    lastUpdated: '2026-07-13T09:15:00Z',
    notes: 'Keep in dry environment. High precision laser sensors.',
    minStock: 15,
  },
  {
    sku: 'SKU-TL-5002',
    name: 'Heavy Duty Steel Cable 12mm',
    quantity: 120,
    unit: 'meter',
    location: 'R2-S3-L2',
    lastUpdated: '2026-07-12T14:30:00Z',
    notes: 'Tested load rating 4000kg. Reel No. 8',
    minStock: 50,
  },
  {
    sku: 'SKU-CH-1085',
    name: 'Polymerized Adhesive Compound X',
    quantity: 8,
    unit: 'kg',
    location: 'R3-S2-L1',
    lastUpdated: '2026-07-13T10:00:00Z',
    notes: 'Low stock warning active. Store at room temperature.',
    minStock: 20,
  },
  {
    sku: 'SKU-ME-4009',
    name: 'Reinforced Aluminum Brackets (Pack of 50)',
    quantity: 65,
    unit: 'box',
    location: 'R1-S4-L3',
    lastUpdated: '2026-07-11T16:45:00Z',
    notes: 'Zinc plated to prevent rust.',
    minStock: 10,
  },
  {
    sku: 'SKU-LI-9004',
    name: 'Degreasing Solvent Clean-Solv',
    quantity: 4,
    unit: 'liters',
    location: 'R4-S5-L2',
    lastUpdated: '2026-07-10T11:20:00Z',
    notes: 'Highly flammable. Keep away from direct sunlight.',
    minStock: 10,
  },
  {
    sku: 'SKU-EL-3012',
    name: 'LED Status Indicators Yellow 24V',
    quantity: 350,
    unit: 'count',
    location: 'R1-S1-L2',
    lastUpdated: '2026-07-09T08:00:00Z',
    notes: 'Standard 24V control panel indicators.',
    minStock: 100,
  },
];

export const INITIAL_MOVEMENTS: Movement[] = [
  {
    id: 'MOV-1001',
    personName: 'Saeed Satari',
    productSku: 'SKU-EL-3001',
    productName: 'Industrial Proximity Sensor V2',
    type: 'IN',
    quantity: 20,
    date: '2026-07-13T09:15:00Z',
    location: 'R1-S1-L1',
    notes: 'Restocked from manufacturer batch B441',
  },
  {
    id: 'MOV-1002',
    personName: 'Amir Hosseini',
    productSku: 'SKU-TL-5002',
    productName: 'Heavy Duty Steel Cable 12mm',
    type: 'OUT',
    quantity: 30,
    date: '2026-07-12T14:30:00Z',
    location: 'R2-S3-L2',
    notes: 'Dispatched for assembly line C',
  },
  {
    id: 'MOV-1003',
    personName: 'Sara Ahmadi',
    productSku: 'SKU-CH-1085',
    productName: 'Polymerized Adhesive Compound X',
    type: 'IN',
    quantity: 5,
    date: '2026-07-13T10:00:00Z',
    location: 'R3-S2-L1',
    notes: 'Emergency procurement from local distributor',
  },
  {
    id: 'MOV-1004',
    personName: 'Saeed Satari',
    productSku: 'SKU-ME-4009',
    productName: 'Reinforced Aluminum Brackets (Pack of 50)',
    type: 'OUT',
    quantity: 15,
    date: '2026-07-11T16:45:00Z',
    location: 'R1-S4-L3',
    notes: 'Released for building project R-A',
  },
];

export const PRESET_USERS = [
  'Saeed Satari',
  'Amir Hosseini',
  'Sara Ahmadi',
  'Reza Mohammadi',
];
